export const APPWRITE_KEYS = {
 API_URL: process.env.EXPO_PUBLIC_API_URL,
 PROJECT_ID: process.env.EXPO_PUBLIC_PROJECT_ID,
 PLATFORM_ID: process.env.EXPO_PUBLIC_PLATFORM_ID,
 DATABASE_ID: process.env.EXPO_PUBLIC_DATABASE_ID,
 TOURS_TABLE_ID: process.env.EXPO_PUBLIC_TOURS_TABLE_ID,
};